/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package dyhelper.com.ui;

import java.util.ArrayList;

import android.app.Activity;
import android.content.Intent;
import android.graphics.Color;
import android.os.Build;
import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.view.ViewGroup;
import android.view.Window;
import android.widget.ImageView;
import cn.dianyou.views.ReboundViewPager;
import xyz.monkeytong.hongbao.R;

public class GuidePageMain extends Activity {
    private static final int[] GUILD_IMAGE_IDS = {R.drawable.guide_icon1, R.drawable.guide_icon2, R.drawable.guide_icon3};
    private ReboundViewPager guidPage;
    private int totalCount = GUILD_IMAGE_IDS.length;
    
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        int currentVersionCode = XYZApplication.getCurrentVersioncode(this);
        int lastVersionCode = XYZApplication.getLastVersionCode(this);
        boolean isFirstInstall = XYZApplication.isFirstInstallApk(this);
        if(!isFirstInstall) {
            if(currentVersionCode <= lastVersionCode) {
                XYZApplication.saveLastVersionCode(this, currentVersionCode);
                int lastVersionCode2 = XYZApplication.getLastVersionCode(this);
                Log.i("chaochao", "localversion:" + lastVersionCode2);
                startActivity(new Intent(this, Main.class));
                finish();
            }
            return;
        }
        XYZApplication.saveLastVersionCode(this, currentVersionCode);
        setContentView(R.layout.activity_guide_page);
        if(Build.VERSION.SDK_INT >= 0x13) {
            Window window = getWindow();
            window.setFlags(0x400, 0x400);
        }
        initViews();
        initDatas();
        setEvents();
    }
    
    private void setEvents() {
    }
    
    private void initDatas() {
        ArrayList<View> listView = new ArrayList<View>();
        listView.addAll(getData());
        totalCount = listView.size();
        guidPage.setPagerViews(listView);
    }
    
    
    private ArrayList<View> getData() {
        ArrayList<View> listView = new ArrayList<View>();
        for(int i = 0; i < GUILD_IMAGE_IDS.length; ++i) {
        	ImageView imageView = new ImageView(this);
            ViewGroup.LayoutParams lp = new ViewGroup.LayoutParams(-0x1, -0x1);
            imageView.setLayoutParams(lp);
            imageView.setScaleType(ImageView.ScaleType.FIT_XY);
            imageView.setImageDrawable(getResources().getDrawable(GUILD_IMAGE_IDS[i]));
            listView.add(imageView);
        }
        
        listView.get((listView.size() - 1)).setOnClickListener(new View.OnClickListener() {
            
            public void onClick(View v) {
            	startMain();
            }
        });
        return listView;
    }
    
    private void initViews() {
        guidPage = (ReboundViewPager)findViewById(R.id.id_guidPage);
        guidPage.setTransitionEffect(ReboundViewPager.TransitionEffect.None);
        guidPage.setFadeEnabled(false);
        guidPage.setIndexDot(true);
        guidPage.setDotCheckedColor(Color.parseColor("#88000000"));
        guidPage.setDotUnCheckedColor(Color.parseColor("#88ffffff"));
        guidPage.setBootAutoGo(false);
        guidPage.setDotSizeRadius(0.005f);
    }
    
    private void startMain() {
        XYZApplication.setIsFirstInstallApk(this, false);
        startActivity(new Intent(this, Main.class));
        finish();
    }
}
