/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package dyhelper.com.ui;

import android.support.v4.app.FragmentActivity;
import android.os.Build;
import android.view.Window;
import android.content.Intent;
import android.os.Bundle;
import android.provider.Settings;
import android.app.FragmentManager;
import android.app.FragmentTransaction;
import android.widget.TextView;
import android.view.View;
import android.app.Fragment;
import dyhelper.com.fragment.GeneralSettingsFragment;
import dyhelper.com.util.SystemBarTintManager;
import xyz.monkeytong.hongbao.R;
import dyhelper.com.fragment.CommentSettingsFragment;
import android.util.Log;

public class SettingsActivity extends FragmentActivity {
    private int activityCloseEnterAnimation;
    private int activityCloseExitAnimation;
    
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(0x7f04001f);
        loadUI();
        prepareSettings();
        int[] activityAniValues = Main.obtrainExitAnims(this);
        activityCloseEnterAnimation = activityAniValues[0x0];
        activityCloseExitAnimation = activityAniValues[0x1];
    }
    
    private void prepareSettings() {
    	String title, fragId;
		Bundle bundle = getIntent().getExtras();
		if (bundle != null) {
			title = bundle.getString("title");
			fragId = bundle.getString("frag_id");
		} else {
			title = "∆´∫√…Ë÷√";
			fragId = "GeneralSettingsFragment";
		}

		TextView textView = (TextView) findViewById(R.id.settings_bar);
		textView.setText(title);

		FragmentManager fragmentManager = getFragmentManager();
		FragmentTransaction fragmentTransaction = fragmentManager
				.beginTransaction();

		if ("GeneralSettingsFragment".equals(fragId)) {
			fragmentTransaction.replace(R.id.preferences_fragment,
					new GeneralSettingsFragment());
		} else if ("CommentSettingsFragment".equals(fragId)) {
			fragmentTransaction.replace(R.id.preferences_fragment,
					new CommentSettingsFragment());
		}
		fragmentTransaction.commit();
    }
    
    private void loadUI() {
        if(Build.VERSION.SDK_INT < Build.VERSION_CODES.LOLLIPOP) {
            return;
        }
        Window window = getWindow();
        window.clearFlags(0x4000000);
        window.addFlags(0x80000000);
        SystemBarTintManager s = new SystemBarTintManager(this);
        s.setStatusBarTintColor(-0x1b939e);
    }
    
    public void finish() {
        super.finish();
        overridePendingTransition(activityCloseEnterAnimation, activityCloseExitAnimation);
        Log.i("INFO", "finish:!");
    }
    
    protected void onResume() {
        super.onResume();
    }
    
    public void performBack(View view) {
        super.onBackPressed();
    }
    
    public void enterAccessibilityPage(View view) {
    	Intent mAccessibleIntent = new Intent(
				Settings.ACTION_ACCESSIBILITY_SETTINGS);
		startActivity(mAccessibleIntent);
    }
}
