/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package dyhelper.com.ui;

import android.app.Activity;
import dyhelper.com.adapter.UserCenterItemAdapter;
import android.widget.ImageView;
import android.widget.ListView;
import android.view.View;
import android.widget.TextView;
import java.util.ArrayList;
import dyhelper.com.bean.UserCenterItem;
import xyz.monkeytong.hongbao.R;
import android.content.res.Resources;
import android.content.res.TypedArray;
import java.util.List;
import android.widget.ListAdapter;
import android.util.Log;
import android.graphics.BitmapFactory;
import android.graphics.Bitmap;
import android.os.Bundle;

public class UserCenter extends Activity {
    private int activityCloseEnterAnimation;
    private int activityCloseExitAnimation;
    private UserCenterItemAdapter adapter;
    private String currentLoginType;
    private ImageView iv_img;
    private ListView listView;
    
    private TextView tv_integral;
    private TextView tv_setPwd;
    private TextView tv_username;
    
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_user_center);
        initViews();
        initEvents();
        setData();
        int[] activityAniValues = Main.obtrainExitAnims(this);
        activityCloseEnterAnimation = activityAniValues[0];
        activityCloseExitAnimation = activityAniValues[1];
    }
    
    private void initEvents() {
        tv_setPwd.setOnClickListener(onClickListener);
    }
    
    private void setData() {
        checkLoginInfo();
        checkItemData();
        checkUserIcon();
    }
    
    private void checkItemData() {
        ArrayList<UserCenterItem> datas = new ArrayList<UserCenterItem>();
        String[] titles = getResources().getStringArray(R.array.user_center_item_titles);
        TypedArray tr = getResources().obtainTypedArray(R.array.user_center_item_icons);
        for(int i = 0; i < tr.length(); ++i) {
        	UserCenterItem item = new UserCenterItem();
            item.setTitle(titles[i]);
            item.setTitleIconId(tr.getResourceId(i, 0));
            datas.add(item);
        }
        
        tr.recycle();
        adapter = new UserCenterItemAdapter(this, datas);
        listView.setAdapter(adapter);
    }
    
    private void checkLoginInfo() {
        String username = XYZApplication.obtainStringInfo(this, "pre_success_user_name");
        tv_username.setText(username);
        currentLoginType = XYZApplication.obtainStringInfo(this, "dianyou_login_current_id_type");
        if(currentLoginType == null) {
            currentLoginType = "0";
        }
        Log.i("INFO", currentLoginType);
    }
    
    private void checkUserIcon() {
        String filepath = XYZApplication.obtainStringInfo(this, "pre_success_user_icon_filepath");
        Log.i("chaochao", filepath);
        Bitmap bmp = null;
        if(filepath == null) {
            if(currentLoginType.equals("2")) {
            	bmp = BitmapFactory.decodeResource(getResources(), R.drawable.login_phone_user_icon);
                iv_img.setImageBitmap(bmp);
                return;
            }
            if(currentLoginType.equals("3")) {
                bmp = BitmapFactory.decodeResource(getResources(), R.drawable.login_phone_user_icon);
                iv_img.setImageBitmap(bmp);
            }
            return;
        }
        bmp = BitmapFactory.decodeFile(filepath);
        if(bmp != null) {
            iv_img.setImageBitmap(bmp);
        }
    }
    
    private void initViews() {
        tv_username = (TextView)findViewById(R.id.id_tv_username);
        tv_integral = (TextView)findViewById(R.id.id_tv_integral);
        tv_setPwd = (TextView)findViewById(R.id.id_setting_pwd);
        iv_img = (ImageView)findViewById(R.id.id_me_img);
        listView = (ListView)findViewById(R.id.id_listview);
    }
    
    public void onUserCenterBack(View v) {
        finish();
        overridePendingTransition(activityCloseEnterAnimation, activityCloseExitAnimation);
    }
    
    public void finish() {
        super.finish();
    }
    
    private void alterPwd() {
        XYZApplication.saveLoginState(this, false);
        XYZApplication.clearCurrentLogin(this);
        finish();
    }
    
    private View.OnClickListener onClickListener = new View.OnClickListener() {
		
		@Override
		public void onClick(View v) {
			alterPwd();
		}
	};
    
    private void setUserIcon() {
    }
}
