/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package dyhelper.com.ui;

import android.app.Application;
import com.tencent.mm.sdk.openapi.IWXAPI;

import xyz.monkeytong.hongbao.wxapi.WXAuthorize;
import dyhelper.com.util.DeviceUtils;
import dyhelper.com.weather.WeatherMain;
import okhttp3.Call;
import android.content.Context;
import android.content.Intent;
import cn.dianyou.utils.SharedPreferencesUtils;
import android.content.pm.PackageManager;
import android.content.pm.PackageInfo;
import android.util.Log;
import dyhelper.com.appsmanager.AppsMain;
import dyhelper.com.bean.DeviceInfo;
import dyhelper.com.bean.PageActLogInfo;
import dyhelper.com.filemanager.explorer.FileManagerMain;

import java.net.URLDecoder;
import java.net.URLEncoder;
import java.util.HashMap;
import java.util.Map;

import org.json.JSONObject;

import cn.dianyou.nets.DYHttpUtils;
import cn.dianyou.nets.DYPostFormBuilder;
import cn.dianyou.nets.DYHttpRequestBuilder;
import cn.dianyou.nets.DYRequestCall;
import cn.dianyou.nets.DYStringCallback;
import cn.dianyou.nets.DYCallback;
import com.tencent.mm.sdk.openapi.WXAPIFactory;

import dyhelper.com.util.Constants;
import dyhelper.com.util.DeviceInfoManager;

public class XYZApplication extends Application {
    private static final String FILENAME_DIANYOU_AUTHORIZE = "filename_dianyou_authorize";
    public static IWXAPI api;
    public static WXAuthorize authorize;
    public static DeviceUtils deviceUtils;
    
    public void onCreate() {
        Log.i("INFO", "XYZApplication-->onCreate");
        super.onCreate();
        if(api == null) {
            api = WXAPIFactory.createWXAPI(this, Constants.WeiXin.APP_ID, false);
            api.registerApp(Constants.WeiXin.APP_ID);
        }
        if(authorize == null) {
            authorize = new WXAuthorize(this);
        }
        if(deviceUtils == null) {
            deviceUtils = new DeviceUtils(this);
        }
        DeviceInfoManager.initDeviceInfo(this);
    }
    
    public static int getCurrentVersioncode(Context context) {
        int versionCode = 1;
        PackageManager pm = context.getPackageManager();
        try {
            PackageInfo info = pm.getPackageInfo(context.getPackageName(), 0x0);
            versionCode = info.versionCode;
            return versionCode;
        } catch(Exception localException1) {
        }
        return versionCode;
    }
    
    static boolean isFirstInstallApk(Context context) {
        SharedPreferencesUtils sp = SharedPreferencesUtils.newInstance(context, FILENAME_DIANYOU_AUTHORIZE);
        return sp.getBoolean(Constants.DianYou.DIANYOU_FIRST_INSTALL_APK_KEY, true);
    }
    
    public static void setIsFirstInstallApk(Context context, boolean isFirstInstall) {
        SharedPreferencesUtils sp = SharedPreferencesUtils.newInstance(context, FILENAME_DIANYOU_AUTHORIZE);
        sp.saveBoolean(Constants.DianYou.DIANYOU_FIRST_INSTALL_APK_KEY, isFirstInstall).commit();
    }
    
    public static void saveLastVersionCode(Context context, int apkcode) {
        SharedPreferencesUtils sp = SharedPreferencesUtils.newInstance(context, FILENAME_DIANYOU_AUTHORIZE);
        sp.saveInt(Constants.DianYou.DIANYOU_LAST_CODE, apkcode).commit();
    }
    
    public static int getLastVersionCode(Context context) {
        SharedPreferencesUtils sp = SharedPreferencesUtils.newInstance(context, FILENAME_DIANYOU_AUTHORIZE);
        return sp.getInt(Constants.DianYou.DIANYOU_LAST_CODE, (getCurrentVersioncode(context) - 0x1));
    }
    
    static boolean checkUniqueId(Context context) {
        String id = obtainStringInfo(context, Constants.DianYou.DIANYOU_UNIQUE_ID);
        return (id != null);
    }
    
    static boolean checkCurrentId(Context context) {
        String id = obtainStringInfo(context, Constants.Login.LOGIN_CURRENT_ID);
        return (id != null);
    }
    
    static void clearCurrentLogin(Context context) {
        SharedPreferencesUtils sp = SharedPreferencesUtils.newInstance(context, FILENAME_DIANYOU_AUTHORIZE);
        sp.saveString(Constants.Login.LOGIN_CURRENT_ID, obtainStringInfo(context, Constants.DianYou.DIANYOU_UNIQUE_ID)).
        saveString(Constants.Login.LOGIN_CURRENT_ID_TYPE, obtainStringInfo(context, Constants.Login.LOGIN_CURRENT_ID_TYPE)).commit();
    }
    
    static boolean checkExistsId(Context context) {
        String id = obtainStringInfo(context, Constants.Login.LOGIN_CURRENT_ID);
        if(id == null) {
            id = obtainStringInfo(context, Constants.DianYou.DIANYOU_UNIQUE_ID);
        }
        return (id != null);
    }
    
    public static boolean checkIsLogin(Context context) {
        SharedPreferencesUtils sp = SharedPreferencesUtils.newInstance(context, FILENAME_DIANYOU_AUTHORIZE);
        return sp.getBoolean(Constants.Login.LOGIN_SUCCESS_FLAG, false);
    }
    
    static void saveLoginState(Context context, boolean isLogin) {
        SharedPreferencesUtils sp = SharedPreferencesUtils.newInstance(context, FILENAME_DIANYOU_AUTHORIZE);
        sp.saveBoolean(Constants.Login.LOGIN_SUCCESS_FLAG, isLogin).commit();
    }
    
    public static void saveInfo(Context context, String key, String value) {
        SharedPreferencesUtils sp = SharedPreferencesUtils.newInstance(context, FILENAME_DIANYOU_AUTHORIZE);
        sp.saveString(key, value).commit();
    }
    
    public static void saveInfo(Context context, String key, boolean value) {
        SharedPreferencesUtils sp = SharedPreferencesUtils.newInstance(context, FILENAME_DIANYOU_AUTHORIZE);
        sp.saveBoolean(key, value).commit();
    }
    
    public static boolean obtainBooleanInfo(Context context, String key) {
        SharedPreferencesUtils sp = SharedPreferencesUtils.newInstance(context, FILENAME_DIANYOU_AUTHORIZE);
        boolean v = sp.getBoolean(key, false);
        return v;
    }
    
    public static String obtainStringInfo(Context context, String key) {
        SharedPreferencesUtils sp = SharedPreferencesUtils.newInstance(context, FILENAME_DIANYOU_AUTHORIZE);
        String v = sp.getString(key, null);
        return v;
    }
    
    static void obtainUniqueIdByPhoneInfo(Context context, XYZApplication.IOnInitListener onInitListener) {
        final Context tempContext = context;
        final IOnInitListener tempOnInitListener = onInitListener;
        String screenW = DeviceInfo.getInstance().getScreen_width();
        String screenH = DeviceInfo.getInstance().getScreen_height();
        String imei = DeviceInfo.getInstance().getImei();
        String imsi = DeviceInfo.getInstance().getImsi();
        String iccid = DeviceInfo.getInstance().getIccid();
        String phone_type = DeviceInfo.getInstance().getPhone_type();
        String phone_operate_system = "android";
        String android_version = DeviceInfo.getInstance().getAndroid_version();
        String api_version = DeviceInfo.getInstance().getApi_version();
        String net_state = DeviceInfo.getInstance().getNet_state();
        String province_code = DeviceInfo.getInstance().getProvince_code();
        String phone_carrier = DeviceInfo.getInstance().getPhone_carrier();
        String version_code = deviceUtils.appVersionCode;
        String version_name = deviceUtils.appVersionName;
        Log.i("INFO", "screenW:" + screenW);
		Log.i("INFO", "screenH:" + screenH);
		Log.i("INFO", "imei:" + imei);
		Log.i("INFO", "imsi:" + imsi);
		Log.i("INFO", "iccid:" + iccid);
		Log.i("INFO", "phone_type:" + phone_type);
		Log.i("INFO", "phone_operate_system:" + phone_operate_system);
		Log.i("INFO", "android_version:" + android_version);
		Log.i("INFO", "api_version:" + api_version);
		Log.i("INFO", "net_state:" + net_state);
		Log.i("INFO", "province_code:" + province_code);
		Log.i("INFO", "phone_carrier:" + phone_carrier);
		Log.i("INFO", "version_code:" + version_code);
		Log.i("INFO", "version_name:" + version_name);
		if(screenW == null)
			screenW = "";
		if(screenH == null)
			screenH = "";
		if(imei == null)
			imei = "";
		if(imsi == null)
			imsi = "";
		if(iccid == null)
			iccid = "";
		if(phone_type == null)
			phone_type = "";
		if(phone_operate_system == null)
			phone_operate_system = "";
		if(android_version == null)
			android_version = "";
		if(net_state == null)
			net_state = "";
		if(province_code == null)
			province_code = "";
		
		if(phone_carrier == null)
			phone_carrier = "";
		if(version_code == null)
			version_code = "";
		if(version_name == null)
			version_name = "";
        try {
            screenW = URLEncoder.encode(screenW, "UTF-8");
            screenH = URLEncoder.encode(screenH, "UTF-8");
            imei = URLEncoder.encode(imei, "UTF-8");
            imsi = URLEncoder.encode(imsi, "UTF-8");
            iccid = URLEncoder.encode(iccid, "UTF-8");
            phone_type = URLEncoder.encode(phone_type, "UTF-8");
            phone_operate_system = URLEncoder.encode(phone_operate_system, "UTF-8");
            android_version = URLEncoder.encode(android_version, "UTF-8");
            api_version = URLEncoder.encode(api_version, "UTF-8");
            net_state = URLEncoder.encode(net_state, "UTF-8");
            province_code = URLEncoder.encode(province_code, "UTF-8");
            phone_carrier = URLEncoder.encode(phone_carrier, "UTF-8");
            version_code = URLEncoder.encode(version_code, "UTF-8");
            version_name = URLEncoder.encode(version_name, "UTF-8");
            HashMap<String, String> params = new HashMap<String, String>();
            params.put("screen_width", screenW);
            params.put("screen_height", screenH);
            params.put("imei", imei);
            params.put("imsi", imsi);
            params.put("iccid", iccid);
            params.put("phone_type", phone_type);
            params.put("phone_operate_system", phone_operate_system);
            params.put("android_version", android_version);
            params.put("api_version", api_version);
            params.put("net_state", net_state);
            params.put("province_code", province_code);
            params.put("phone_carrier", phone_carrier);
            params.put("version_code", version_code);
            params.put("version_name", version_name);
            Log.i("INFO", "version_name" + params);
            Log.i("INFO", "...url...:" + Constants.Dianyou_url.URL_PHONE);
            DYHttpUtils.getInstance().post().url(Constants.Dianyou_url.URL_PHONE).paramJSONType().params(params).build().execute(new DYStringCallback() {
				
				@Override
				public void onResponse(String data, int arg1) {
					
					Log.i("INFO", "............data:" + data);
					
					try {
						data = URLDecoder.decode(data, "UTF-8");
						Log.i("INFO", "data:" + data);
						JSONObject jsonObject = new JSONObject(data);
						int code = jsonObject.getInt("Code");
						if(code == 0) {
							String uniqueId = jsonObject.optString("Id");
							String uniqueIdType = String.valueOf(jsonObject.optInt("Type"));
							Log.i("INFO", "uniqueId:" + uniqueId);
							//保存在本地
							saveInfo(tempContext, Constants.Keys.DIANYOU_UNIQUE_ID, uniqueId);
							saveInfo(tempContext, Constants.Keys.DIANYOU_UNIQUE_ID_TYPE, uniqueIdType);
							excuteListener(tempOnInitListener, uniqueId, uniqueIdType);
						} else {
							excuteListener(tempOnInitListener, obtainStringInfo(tempContext, Constants.Keys.DIANYOU_UNIQUE_ID), obtainStringInfo(tempContext, Constants.Keys.DIANYOU_UNIQUE_ID_TYPE));
						}
					} catch (Exception e) {
						Log.i("INFO", "obtainUniqueIdByPhoneInfo->onResponse ex:" + e.toString());
						excuteListener(tempOnInitListener, obtainStringInfo(tempContext, Constants.Keys.DIANYOU_UNIQUE_ID), obtainStringInfo(tempContext, Constants.Keys.DIANYOU_UNIQUE_ID_TYPE));
							
					}
						
				}
				
				@Override
				public void onError(Call arg0, Exception arg1, int arg2) {
					Log.i("INFO", "fail......:" + arg1.toString());
					excuteListener(tempOnInitListener, obtainStringInfo(tempContext, Constants.Keys.DIANYOU_UNIQUE_ID), obtainStringInfo(tempContext, Constants.Keys.DIANYOU_UNIQUE_ID_TYPE));
					
				}
			});
            return;
        } catch(Exception e) {
            excuteListener(tempOnInitListener, obtainStringInfo(tempContext, Constants.Keys.DIANYOU_UNIQUE_ID), obtainStringInfo(tempContext, Constants.Keys.DIANYOU_UNIQUE_ID_TYPE));
        }
    }
    
    private static void excuteListener(XYZApplication.IOnInitListener iOnInitListener, String uniqueId, String uniqueIdType) {
        if(iOnInitListener == null) {
            return;
        }
        if(uniqueId != null) {
        	iOnInitListener.uniqueIdSuccess(uniqueId, uniqueIdType);
            return;
        }
        iOnInitListener.uniqueIdFail(uniqueId, uniqueIdType);
    }
    
    
    public void onTerminate() {
        super.onTerminate();
        api.unregisterApp();
        api = null;
        deviceUtils = null;
        authorize = null;
        Log.i("chaochao", "onTerminate......");
    }
    
    
    public interface IOnInitListener {
		void uniqueIdSuccess(String uniqueId, String uniqueIdType);
		void uniqueIdFail(String uniqueId, String uniqueIdType);
	}
	
	public static class SimpleOnInitListener implements IOnInitListener {

		@Override
		public void uniqueIdSuccess(String uniqueId, String uniqueIdType) {
		}

		@Override
		public void uniqueIdFail(String uniqueId, String uniqueIdType) {
		}
		
	}
}
