/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package dyhelper.com.bean;

import android.content.Context;
import org.json.JSONException;
import cn.dianyou.utils.SharedPreferencesUtils;
import org.json.JSONObject;

public class ConfigInfo {
    private static final String CONFIG_FILE_NAME = "cofigInfo";
    private static final String DIANYOU_CONFIG_INFO = "dianyou_config_info";
    public static final String ERROR_URL = "file:///android_asset/network_error.html";
    public static final int TYPE_GAME_URL = 2;
    public static final int TYPE_NEW_URL = 3;
    public static final int TYPE_SHOP_URL = 1;
    private String weiXinHongBaoFlag;
    private String shopUrl = "file:///android_asset/network_error.html";
    private String gameUrl = "file:///android_asset/network_error.html";
    private String newUrl = "file:///android_asset/network_error.html";
    
    public ConfigInfo(String weiXinHongBaoFlag, String shopUrl, String gameUrl, String newUrl) {
        this.weiXinHongBaoFlag = weiXinHongBaoFlag;
        this.shopUrl = shopUrl;
        this.gameUrl = gameUrl;
        this.newUrl = newUrl;
    }
    
    public ConfigInfo() {
    }
    
    public boolean isErrorUrl(int urlType) {
        switch(urlType) {
        case TYPE_SHOP_URL:
        {
            return shopUrl.equals("file:///android_asset/network_error.html");
        }
        case TYPE_GAME_URL:
        {
            return gameUrl.equals("file:///android_asset/network_error.html");
        }
        case TYPE_NEW_URL:
        {
            return newUrl.equals("file:///android_asset/network_error.html");
        }
        }
        return false;
    }
    
    public String getWeiXinHongBaoFlag() {
        return weiXinHongBaoFlag;
    }
    
    public void setWeiXinHongBaoFlag(String weiXinHongBaoFlag) {
        this.weiXinHongBaoFlag = weiXinHongBaoFlag;
    }
    
    public String getShopUrl() {
        return shopUrl;
    }
    
    public void setShopUrl(String shopUrl) {
        this.shopUrl = shopUrl;
    }
    
    public String getGameUrl() {
        return gameUrl;
    }
    
    public void setGameUrl(String gameUrl) {
        this.gameUrl = gameUrl;
    }
    
    public String getNewUrl() {
        return newUrl;
    }
    
    public void setNewUrl(String newUrl) {
        this.newUrl = newUrl;
    }
    
    public void saveToShare(Context context) {
        SharedPreferencesUtils spu = SharedPreferencesUtils.newInstance(context, CONFIG_FILE_NAME);
        spu.saveString(DIANYOU_CONFIG_INFO, toString()).commit();
    }
    
    public boolean recoverFromShare(Context context) {
    	 SharedPreferencesUtils spu = SharedPreferencesUtils.newInstance(context, CONFIG_FILE_NAME);
    	 String data = spu.getString(DIANYOU_CONFIG_INFO, "");
    	 if(!"".equals(data)) {
    		 try {
    			 JSONObject jsonObj = new JSONObject(data);
    			 	weiXinHongBaoFlag = jsonObj.getString("weiXinHongBaoFlag");
    			 	shopUrl = jsonObj.getString("ShopUrl");
    			 	gameUrl = jsonObj.getString("GameUrl");
    			 	newUrl = jsonObj.getString("NewUrl");
    			 	return true;
    		 } catch(Exception e) {
    		 }
    	 }
    	 return false;
    }
    
    public String toString() {
        return "{\"" + weiXinHongBaoFlag + "\":\"" + weiXinHongBaoFlag + "\", \"ShopUrl\": \"" + shopUrl + "\", \"GameUrl\": \"" + gameUrl + "\", \"NewUrl\": \"" + newUrl + "\"}";
    }
}
