/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package dyhelper.com.bean;

import android.graphics.Bitmap;

public class ImageInfo implements Comparable<ImageInfo> {
    private Bitmap bitmap;
    private int sort;
    private String title;
    private String url;
    
    public ImageInfo(String title, String url, int sort) {
        this.title = title;
        this.url = url;
        this.sort = sort;
    }
    
    public String getTitle() {
        return title;
    }
    
    public void setTitle(String title) {
    	this.title = title;
    }
    
    public String getUrl() {
        return url;
    }
    
    public void setUrl(String url) {
    	this.url = url;
    }
    
    public int getSort() {
        return sort;
    }
    
    public void setSort(int sort) {
    	this.sort = sort;
    }
    
    public Bitmap getBitmap() {
        return bitmap;
    }
    
    public void setBitmap(Bitmap bitmap) {
    	this.bitmap = bitmap;
    }
    
    @Override
	public String toString() {
		return "ImageInfo [bitmap=" + bitmap + ", sort=" + sort + ", title=" + title + ", url=" + url + "]";
	}

	public int compareTo(ImageInfo another) {
        if(sort == another.sort) {
            return 0;
        }
        return sort < another.sort ? -1 : 1;
    }
}
