/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package dyhelper.com.bean;


public class UserCenterItem {
    private String title;
    private int titleIconId;
    
    public UserCenterItem() {}
    
    public UserCenterItem(String title, int titleIconId) {
        this.title = title;
        this.titleIconId = titleIconId;
    }
    
    public String getTitle() {
        return title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    
    public int getTitleIconId() {
        return titleIconId;
    }
    
    public void setTitleIconId(int titleIconId) {
        this.titleIconId = titleIconId;
    }
}
