/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package dyhelper.com.broadcasts;

import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;
import android.util.Log;
import android.net.ConnectivityManager;
import android.net.NetworkInfo;

public class NetworkChangeReceiver extends BroadcastReceiver {
    private NetworkChangeReceiver.IOnNetworkChangeListener listener;
    private boolean isEnable = true;
    
    public NetworkChangeReceiver(IOnNetworkChangeListener onNetworkChangeListener) {
        listener = onNetworkChangeListener;
    }
    
    public void onReceive(Context context, Intent intent) {
        Log.i("chaochao", "NetworkChangeReceiver-->onReceive");
        if(intent.getAction().equals("android.net.conn.CONNECTIVITY_CHANGE")) {
            Log.i("chaochao", "\u7f51\u7edcchange\u76d1\u542c\u5230\u4e86");
            ConnectivityManager connectivityManager = (ConnectivityManager) context.getSystemService("connectivity");
            if(connectivityManager == null) {
                return;
            }
            NetworkInfo info = connectivityManager.getActiveNetworkInfo();
            if((info != null) && (info.isAvailable())) {
                Log.i("chaochao", "\u6709\u7f51\u7edc \u5237\u65b0");
                if(listener != null) {
                    listener.openNetwork();
                }
                return;
            }
            Log.i("chaochao", "\u65e0\u7f51\u7edc close");
            if(listener != null) {
                listener.closeNetwork();
            }
        }
    }
    
    public void setOnNetworkChangeListener(IOnNetworkChangeListener onNetworkChangeListener) {
        listener = onNetworkChangeListener;
    }
    
    public interface IOnNetworkChangeListener {
    	void openNetwork();
    	void closeNetwork();
    }
}
