/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package dyhelper.com.view;

import android.view.SurfaceView;
import android.view.SurfaceHolder;
import android.hardware.Camera;
import android.content.Context;
import android.util.AttributeSet;

public class FlashlightSurface extends SurfaceView implements SurfaceHolder.Callback {
    private Camera mCameraDevices;
    private SurfaceHolder mHolder;
    private Camera.Parameters mParameters;
    
    public FlashlightSurface(Context context, AttributeSet attrs) {
        super(context, attrs);
        mHolder = getHolder();
        mHolder.addCallback(this);
        mHolder.setType(0x3);
    }
    
    public FlashlightSurface(Context context) {
        this(context, null);
    }
    
    public void surfaceChanged(SurfaceHolder holder, int format, int width, int height) {
        mParameters = mCameraDevices.getParameters();
        if(mParameters != null) {
            mParameters.setPictureFormat(0x100);
        }
        mParameters.setPreviewSize(0x140, 0x1e0);
        mParameters.setPictureSize(0x140, 0x1e0);
        mCameraDevices.setParameters(mParameters);
        mCameraDevices.startPreview();
    }
    
    public void surfaceCreated(SurfaceHolder holder) {
        try {
            mCameraDevices = Camera.open();
            mCameraDevices.setPreviewDisplay(mHolder);
            return;
        } catch(Exception e) {
            if(mCameraDevices != null) {
                mCameraDevices.release();
            }
            mCameraDevices = null;
        }
    }
    
    public void surfaceDestroyed(SurfaceHolder holder) {
        if(mCameraDevices == null) {
            return;
        }
        mCameraDevices.stopPreview();
        mCameraDevices.release();
        mCameraDevices = null;
    }
    
    public void setFlashlightSwitch(boolean on) {
        if(mCameraDevices == null) {
            return;
        }
        if(mParameters == null) {
            mParameters = mCameraDevices.getParameters();
        }
        if(on) {
            mParameters.setFlashMode("torch");
        } else {
            mParameters.setFlashMode("off");
        }
        mCameraDevices.setParameters(mParameters);
    }
}
