/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package dyhelper.com.view;

import android.widget.FrameLayout;
import android.content.Context;
import android.util.AttributeSet;

public class InhalationLayout extends FrameLayout {
    
    public InhalationLayout(Context context) {
        this(context, null);
    }
    
    public InhalationLayout(Context context, AttributeSet attrs) {
        this(context, attrs, 0x0);
    }
    
    public InhalationLayout(Context context, AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);
        obtainScreenInfo(context);
        initPaint();
    }
    
    private void obtainScreenInfo(Context context) {
    }
    
    private void initPaint() {
    }
}
