/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package dyhelper.com.view;

import android.widget.ListView;
import android.graphics.Paint;
import android.content.Context;
import android.util.AttributeSet;
import android.graphics.Color;
import android.graphics.Canvas;

public class LineListView extends ListView {
    private float dividerHeight;
    private Paint paint;
    
    public LineListView(Context context) {
        this(context, null);
    }
    
    public LineListView(Context context, AttributeSet attrs) {
        this(context, attrs, 0x0);
    }
    
    public LineListView(Context context, AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);
        initPaint();
    }
    
    private void initPaint() {
        paint = new Paint();
        paint.setStyle(Paint.Style.STROKE);
        paint.setStrokeWidth(1.0f);
        paint.setDither(true);
        paint.setAntiAlias(true);
        paint.setColor(Color.parseColor("#66aaaaaa"));
    }
    
    protected void onSizeChanged(int w, int h, int oldw, int oldh) {
        super.onSizeChanged(w, h, oldw, oldh);
        dividerHeight = ((float)getDividerHeight() * 0x3e99999a);
    }
    
    protected void dispatchDraw(Canvas canvas) {
        super.dispatchDraw(canvas);
        canvas.drawLine(0.0f, dividerHeight, (float)getWidth(), dividerHeight, paint);
        canvas.drawLine(0.0f, ((float)getHeight() - dividerHeight), (float)getWidth(), ((float)getHeight() - dividerHeight), paint);
    }
}
