/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package dyhelper.com.weather;

import android.app.Activity;
import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;
import android.widget.ImageView;
import android.widget.Toast;
import android.content.IntentFilter;
import android.os.Bundle;
import android.util.Log;
import dyhelper.com.util.DialogUtils;
import xyz.monkeytong.hongbao.R;
import android.view.View;

public class WeatherMain extends Activity {
    private BroadcastReceiver broadcastReceiver;
    private ImageView ivBack;
    private UIupdater uiupdater;
    public static String LOCATION_BCR = "location_bcr";
    
    protected void onDestroy() {
        super.onDestroy();
        if(broadcastReceiver != null) {
            unregisterReceiver(broadcastReceiver);
            broadcastReceiver = null;
        }
        if(uiupdater != null) {
            uiupdater.clear();
            uiupdater = null;
        }
        System.gc();
    }
    
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        requestWindowFeature(1);
        init();
        Log.i("INFO", "onCreate....");
        if(UIupdater.checkEmpty(this)) {
            new UIupdater(this).update();
            DialogUtils.showDialog(this, null, "\u6b63\u5728\u5b9a\u4f4d\u4e2d...", false);
            findLocation();
        }
    }
    
    private void findLocation() {
        myBDlocation m = new myBDlocation(this);
        m.requestLocationInfo();
    }
    
    private void init() {
        registerBroadCastReceiver();
    }
    
    private void registerBroadCastReceiver() {
        if(broadcastReceiver != null) {
            return;
        }
        broadcastReceiver = new BroadcastReceiver() {
            
            public void onReceive(Context context, Intent intent) {
                String address = intent.getStringExtra("address");
                if(!address.endsWith("ÊÐ")) address += "ÊÐ";
                if(UIupdater.checkCity(WeatherMain.this, address)) {
                    return;
                }
                if(address != null) {
                    Toast.makeText(WeatherMain.this, address, 0).show();
                } else {
                    Toast.makeText(WeatherMain.this, "\u5b9a\u4f4d\u5931\u8d25,\u68c0\u67e5\u7f51\u7edc\u662f\u5426\u5f00\u542f", 0x0).show();
                }
                if(uiupdater != null) {
                    uiupdater.clear();
                }
                UIupdater uiupdater = new UIupdater(WeatherMain.this);
                UIupdater.saveCity(WeatherMain.this, address);
                View view = uiupdater.update();
                uiupdater.setCurrentPosition(UIupdater.getPositionByCity(WeatherMain.this, address));
                ivBack = (ImageView)view.findViewById(R.id.id_back);
                ivBack.setOnClickListener(new View.OnClickListener() {
                    
                    public void onClick(View v) {
                        WeatherMain.this.finish();
                    }
                });
                setContentView(view);
                DialogUtils.closeDialog(WeatherMain.this);
            }
        };
        IntentFilter intentToReceiveFilter = new IntentFilter();
        intentToReceiveFilter.addAction(LOCATION_BCR);
        registerReceiver(broadcastReceiver, intentToReceiveFilter);
    }
    
    protected void onStart() {
        Log.i("INFO", "onStart....");
        if(uiupdater != null) {
            uiupdater.clear();
        }
        uiupdater = new UIupdater(this);
        setContentView(uiupdater.update());
        ivBack = (ImageView)findViewById(R.id.id_back);
        ivBack.setOnClickListener(new View.OnClickListener() {
            
            public void onClick(View v) {
                finish();
            }
        });
        super.onStart();
    }
}
