/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package dyhelper.com.appsmanager;

import android.widget.ImageView;
import android.widget.TextView;
import xyz.monkeytong.hongbao.R;
import android.widget.BaseAdapter;
import java.util.List;
import android.content.Context;
import android.graphics.Bitmap;
import android.view.View;
import android.view.ViewGroup;
import android.view.WindowManager;
import android.view.LayoutInflater;


public class AppListAdapter extends BaseAdapter {

	private List<AppInfo> appList;
	private Context context;

	private ViewHolder holder;

	public AppListAdapter(List<AppInfo> appList, Context context) {
		super();
		this.appList = appList;
		this.context = context;
	}

	class ViewHolder {
		ImageView iv_icon;
		TextView tv_aName;
		TextView tv_pName;
	}

	@Override
	public int getCount() {
		return appList.size();
	}

	@Override
	public Object getItem(int position) {
		return appList.get(position);
	}

	@Override
	public long getItemId(int position) {
		return position;
	}

	@SuppressWarnings("deprecation")
	@Override
	public View getView(int position, View convertView, ViewGroup parent) {

		if (convertView == null) {
			convertView = LayoutInflater.from(context).inflate(
					R.layout.appsmanager_item, null);
			holder = new ViewHolder();
			holder.iv_icon = (ImageView) convertView.findViewById(R.id.iv_icon);
			holder.tv_aName = (TextView) convertView
					.findViewById(R.id.tv_appName);
			holder.tv_pName = (TextView) convertView
					.findViewById(R.id.tv_packageName);
			convertView.setTag(holder);
		} else {
			holder = (ViewHolder) convertView.getTag();
		}

		AppInfo i = (AppInfo) getItem(position);

		// holder.iv_icon.setImageDrawable(i.getIcon());
		// 匹配不同应用icon的大小
		int size = ((WindowManager) context
				.getSystemService(Context.WINDOW_SERVICE)).getDefaultDisplay()
				.getWidth() / 6;
		Bitmap iconBitmap = Bitmap.createScaledBitmap(
				DrawableUtil.drawableToBitmap(i.getIcon()), size, size, true);
		holder.iv_icon.setImageBitmap(iconBitmap);
		holder.tv_aName.setText(i.getAppName());
		holder.tv_pName.setText(i.getPackageName());

		return convertView;
	}
}

