/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package dyhelper.com.appsmanager;

import java.util.ArrayList;
import java.util.List;

import android.app.Activity;
import android.content.Intent;
import android.net.Uri;
import android.os.Bundle;
import android.os.Handler;
import android.os.Message;
import android.view.View;
import android.widget.AdapterView;
import android.widget.AdapterView.OnItemClickListener;
import android.widget.ListView;
import xyz.monkeytong.hongbao.R;

public class AppsMain extends Activity {
    private ListView lv;
	final private Handler mHandler = new Handler() {

		@SuppressWarnings("unchecked")
		@Override
		public void handleMessage(Message msg) {
			super.handleMessage(msg);
			if (msg.what == 1) {

				AppListAdapter adapter = new AppListAdapter(
						(List<AppInfo>) msg.obj, getApplicationContext());

				lv.setAdapter(adapter);
				lv.setOnItemClickListener(new OnItemClickListener() {

					@Override
					public void onItemClick(AdapterView<?> parent, View view,
							int position, long id) {
						AppInfo appInfo = (AppInfo) parent
								.getItemAtPosition(position);

						String packageName = appInfo.getPackageName();

						// É¾³ýÓ¦ÓÃ
						Uri uri = Uri.parse("package:" + packageName);
						Intent intent = new Intent(Intent.ACTION_DELETE, uri);
						AppsMain.this.startActivity(intent);

					}
				});

				pb_wrapper.setVisibility(View.GONE);
				lv.setVisibility(View.VISIBLE);
			}
		}

	};
    private View pb_wrapper;
    
    protected void onDestroy() {
        super.onDestroy();
        mHandler.removeMessages(1);
        lv = null;
        pb_wrapper = null;
        System.gc();
    }
    
    public void performBack(View v) {
        finish();
    }
    
    @Override
    protected void onStart() {
    	super.onStart();
    	new LoadAppInfoTask(this, mHandler, new ArrayList<AppInfo>())
		.execute(false);
    }
    
    protected void onCreate(Bundle savedInstanceState) {
    	super.onCreate(savedInstanceState);
		setContentView(R.layout.appsmanager_main);

		lv = (ListView) findViewById(R.id.lv);
		pb_wrapper = findViewById(R.id.pb_wrapper);
    }
}
