/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package dyhelper.com.appsmanager;

import java.io.File;
import java.util.Collections;
import java.util.List;

import android.content.Context;
import android.content.pm.ApplicationInfo;
import android.content.pm.PackageInfo;
import android.content.pm.PackageManager;
import android.os.AsyncTask;
import android.os.Handler;
import android.os.Message;
import android.util.Log;

public class LoadAppInfoTask extends AsyncTask<Boolean, Integer, String> {

	private Context context;
	private Handler handler;
	private List<AppInfo> appList;
	private String TAG = "LoadAppInfoTask";

	public LoadAppInfoTask(Context context, Handler handler,
			List<AppInfo> appList) {
		super();
		this.context = context;
		this.handler = handler;
		this.appList = appList;
		if (!this.appList.isEmpty()) {
			appList.clear();
		}
	}

	@Override
	protected String doInBackground(Boolean... params) {
		PackageManager pm = context.getPackageManager();
		List<PackageInfo> list = pm.getInstalledPackages(0);
		for (PackageInfo packageInfo : list) {
			// 只加载非系统应用
			if ((packageInfo.applicationInfo.flags & ApplicationInfo.FLAG_SYSTEM) == 0) {
				AppInfo i = new AppInfo();
				i.setPackageName(packageInfo.packageName);
				i.setAppName(pm
						.getApplicationLabel(packageInfo.applicationInfo)
						.toString());
				// 在API 9 (2.3)中加入
				// i.setFirstInstallTime(packageInfo.firstInstallTime);
				i.setFirstInstallTime(new File(
						packageInfo.applicationInfo.sourceDir).lastModified());
				i.setIcon(pm.getApplicationIcon(packageInfo.applicationInfo));
				i.setVersionCode(packageInfo.versionCode);
				appList.add(i);
			} else {
				Log.v(TAG, "忽略系统应用");
			}

		}

		if (appList != null) {
			Collections.sort(appList, new AppInfoComparator());
		}

		return null;
	}

	@Override
	protected void onPostExecute(String result) {
		super.onPostExecute(result);
		Message msg = handler.obtainMessage();
		msg.what = 0x00000001;
		msg.obj = appList;
		handler.sendMessage(msg);
	}

}
