/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package dyhelper.com.util;

import java.util.Map;
import android.app.Activity;
import java.util.HashMap;
import java.util.Collection;
import java.util.Iterator;

public class ActivityCollectorUtils {
    public static Map<String, Activity> activitys = new HashMap<String, Activity>();
    
    public static void addActivity(String key, Activity activity) {
        activitys.put(key, activity);
    }
    
    public static void removeActivity(String key) {
        activitys.remove(key);
    }
    
    public static void removeAllActivity() {
        activitys.clear();
    }
    
    public static void finishAndClear(String key) {
        Activity activity = (Activity)activitys.get(key);
        if(activity != null) {
            activity.finish();
        }
        activitys.remove(key);
    }
    
    public static void finish(String key) {
        Activity activity = (Activity)activitys.get(key);
        if(activity != null) {
            activitys.remove(key);
        }
    }
    
    public static void finishAll(boolean isClear) {
    	for (Activity activity : activitys.values()) {
			if (!activity.isFinishing()) {
				activity.finish();
			}
		}
		
    	if(isClear)
    		activitys.clear();
    }
}
