/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package dyhelper.com.util;


public class Constants {
	public final class Activitys {
		public static final String ACTIVITY_LOGIN = "dianyou_activity_login";
		public static final String ACTIVITY_PHONE_VERIFICATION = "dianyou_activity_phone_verification";
	}
	
	public final class DianYou {
		public static final String DIANYOU_FIRST_INSTALL_APK_KEY = "dianyou_first_install_apk_key";
		public static final String DIANYOU_LAST_CODE = "dianyou_last_code";
		public static final String DIANYOU_UNIQUE_ID = "dianyou_unique_id";
		public static final String DIANYOU_UNIQUE_ID_TYPE = "dianyou_unique_id_type";
	}
	
	public static final class OperationLogPage {
		public static final String[] hongbao = {"1", "抢红包"};
		public static final String[] weather = {"2", "天气"};
		public static final String[] indiana = {"3", "(HTML5)夺宝"};
		public static final String[] filemanager = {"4", "文件管理页面"};
		public static final String[] delapp = {"5", "程序卸载"};
		public static final String[] discover = {"6", "(HTML5)发现"};
		public static final String[] application = {"7", "(HTML5)应用"};
		public static final String[] flashlight = {"8", "(HTML5)手电筒"};
		public static final String[] add = {"9", "添加"};
	}
	
	public static final class Keys {
		
		public static final String WEIXIN_ACCESS_TOKEN_KEY = "weixin_access_token";
		public static final String WEIXIN_OPEN_ID_KEY = "weixin_open_id";
		public static final String WEIXIN_REFRESH_TOKEN_KEY = "weixin_refresh_token";
		public static final String WEIXIN_EXPIRES_IN_KEY = "weixin_expires_in";
		public static final String WEIXIN_SCOPE = "weixin_scope";
		
		public static final String DIANYOU_UNIQUE_ID = "dianyou_unique_id";
		public static final String DIANYOU_UNIQUE_ID_TYPE = "dianyou_unique_id_type";
	}
	
	public final class Dianyou_url {
		public static final String URL_GET_PHONE = "http://azzs.mtkgame.com/User/GetVerificationCode.ashx";
		public static final String URL_INIT = "http://azzs.mtkgame.com/User/Init.ashx";
		public static final String URL_PHONE = "http://azzs.mtkgame.com/User/MobilePhoneInfo.ashx";
		public static final String URL_POST_PHONE = "http://azzs.mtkgame.com/User/PostVerificationCode.ashx";
		public static final String URL_WEIXIN = "http://azzs.mtkgame.com/User/WeiXinLogin.ashx";
		public static final String URL_OPERATION_LOG = "http://azzs.mtkgame.com/Log/OperationLog.ashx";
		public static final String URL_GET_VERSION = "http://azzs.mtkgame.com/User/GetVersion.ashx";
	}
	
	
	public final class FileInfo {
		public static final String CURRENT_SIMPLE_HEADER_IMAGE_DIR = "dianyou_simple_header_image_dir";
		public static final String CURRENT_SIMPLE_ICON_DIR = "dianyou_simple_icon_dir";
		public static final int DELETE_COUNT = 5;
		public static final int DELETE_LIMIT_COUNT = 30;
	}
	
	public final class Login {
		public static final String LOGIN_CURRENT_ID = "dianyou_login_current_id";
		public static final String LOGIN_CURRENT_ID_TYPE = "dianyou_login_current_id_type";
		public static final String LOGIN_FEEUSER_ID = "dianyou_login_feeuser_id";
		public static final String LOGIN_FEEUSER_ID_TYPE = "dianyou_login_feeuserid_type";
		public static final String LOGIN_PHONE_ID = "dianyou_login_phone_id";
		public static final String LOGIN_PHONE_ID_TYPE = "dianyou_login_phone_id_type";
		public static final String LOGIN_SUCCESS_FLAG = "dianyou_login_success_flag";
		public static final String LOGIN_WEIXIN_ID = "dianyou_login_weixin_id";
		public static final String LOGIN_WEIXIN_ID_TYPE = "dianyou_login_weixin_id_type";
	}
	
	public final class UserInfo {
		public static final String CURRENT_USER_ICON_STR = "pre_success_user_icon_filepath";
		public static final String CURRENT_USER_NAME = "pre_success_user_name";
	}
	
	public final class WeiXin {
		public static final String APP_ID = "wx4fcdf0148cb7fc6b";
		public static final String APP_SECRET = "655c7f88f22dd762681952f5d7bfee05";
		public static final String WEIXIN_ACCESS_TOKEN_KEY = "weixin_access_token";
		public static final String WEIXIN_EXPIRES_IN_KEY = "weixin_expires_in";
		public static final String WEIXIN_OPEN_ID_KEY = "weixin_open_id";
		public static final String WEIXIN_REFRESH_TOKEN_KEY = "weixin_refresh_token";
		public static final String WEIXIN_SCOPE = "weixin_scope";
	}
	
	
}
