/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package dyhelper.com.util;

import android.content.Context;
import android.app.AlertDialog;
import android.widget.Toast;

public class MyToast {
    
    public static void showToast(Context context, String str) {
        Toast.makeText(context, str, 0x1).show();
    }
    
    public static void showAlert(Context context, String title, String str) {
        AlertDialog.Builder localAlertDialog1 = new AlertDialog.Builder(context);
        localAlertDialog1 = localAlertDialog1.setIcon(0x7f020117).setTitle(title);
        localAlertDialog1.setIcon(0x7f020117).setMessage(str).create().show();
    }
}
