/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package dyhelper.com.adapter;

import android.widget.ImageView;
import android.widget.TextView;
import android.widget.BaseAdapter;
import android.content.Context;
import android.view.LayoutInflater;
import java.util.List;
import dyhelper.com.bean.UserCenterItem;
import xyz.monkeytong.hongbao.R;
import android.view.View;
import android.view.ViewGroup;

public class UserCenterItemAdapter extends BaseAdapter {
    private Context context;
    private LayoutInflater layoutInflater;
    private List<UserCenterItem> listItems;
    
    public UserCenterItemAdapter(Context context, List<UserCenterItem> listItems) {
        this.context = context;
        layoutInflater = LayoutInflater.from(context);
        this.listItems = listItems;
    }
    
    public int getCount() {
        return listItems == null ? 0 : listItems.size();
    }
    
    public UserCenterItem getItem(int position) {
        return (UserCenterItem)listItems.get(position);
    }
    
    public long getItemId(int position) {
        return position;
    }
    
    public View getView(int position, View convertView, ViewGroup parent) {
        UserCenterItemAdapter.ViewHolder viewHolder = null;
        if(convertView == null) {
            viewHolder = new ViewHolder();
            convertView = layoutInflater.inflate(R.layout.listview_user_center_item, parent, false);
            viewHolder.titleIconIv = (ImageView)convertView.findViewById(R.id.id_uc_item_iv);
            viewHolder.titleTv = (TextView)convertView.findViewById(R.id.id_uc_item_title);
            viewHolder.goIv = (ImageView)convertView.findViewById(R.id.id_uc_item_go_iv);
            convertView.setTag(viewHolder);
        } else {
            viewHolder = (ViewHolder) convertView.getTag();
        }
        viewHolder.titleIconIv.setImageResource(listItems.get(position).getTitleIconId());
        viewHolder.titleTv.setText(listItems.get(position).getTitle());
        return convertView;
    }
    
    final class ViewHolder {
    	public ImageView titleIconIv;
    	public TextView titleTv;
    	public ImageView goIv;
    }
}
