/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package dyhelper.com.fragment;

import android.preference.PreferenceFragment;
import android.preference.Preference;
import android.preference.CheckBoxPreference;
import android.content.res.Resources;
import android.app.Activity;
import android.preference.PreferenceManager;
import xyz.monkeytong.hongbao.R;
import android.content.Context;
import android.content.SharedPreferences;
import android.os.Bundle;

public class GeneralSettingsFragment extends PreferenceFragment {
    
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        addPreferencesFromResource(R.xml.general_preferences);
        setPrefListeners();
    }
    
    private void setPrefListeners() {
        CheckBoxPreference watchChatPf = (CheckBoxPreference)findPreference("pref_watch_chat");
        watchChatPf.setOnPreferenceChangeListener(new Preference.OnPreferenceChangeListener() {
            
            public boolean onPreferenceChange(Preference preference, Object newValue) {
              //  boolean value = Boolean.valueOf((Boolean)newValue);
                return true;
            }
        });
        Preference excludeWordsPref = findPreference("pref_watch_exclude_words");
        String summary = getResources().getString(R.string.pref_watch_exclude_words_summary);
        String value = PreferenceManager.getDefaultSharedPreferences(getActivity()).getString("pref_watch_exclude_words", "");
        if(value.length() > 0) {
            excludeWordsPref.setSummary(":" + value);
        }
        excludeWordsPref.setOnPreferenceChangeListener(new Preference.OnPreferenceChangeListener() {
            
            public boolean onPreferenceChange(Preference preference, Object o) {
                String summary = getResources().getString(R.string.pref_watch_exclude_words_summary);
                if((o != null) && (o.toString().length() > 0)) {
                    preference.setSummary(":" + o.toString());
                } else {
                    preference.setSummary(summary);
                }
                return true;
            }
        });
    }
}
